### ISSUE TITLE
Change from linklocal to dhcp doesn't trigger lease renewal

### ISSUE THREAD

**Issue by electricshaman** [nerves-project/nerves_network#28]
Connecting to a `rpi0` device via serial and changing the `ipv4_address_method` from `:linklocal` to `:dhcp` requires an additional manual step to trigger the lease renewal through `Nerves.Network.Udhcpc`.  Also, there are several errors that follow after calling the renew function on `Nerves.Network.Udhcpc` manually which should be investigated.

```
Nerves:           0.7.2
Nerves Bootstrap: 0.6.1
Elixir:           1.5.0
Nerves Network:   0.3.3
```

### Steps to reproduce (rpi0 + Mac OSX 10.12.6)

1. Setup internet sharing in OSX for the `CDC Composite Gadget`.
2. Start the rpi0 up with `ipv4_address_method` set to `:linklocal`.

3.
```
iex> Nerves.Network.setup :usb0, ipv4_address_method: :dhcp
iex> :os.cmd('ip addr') |> IO.puts
(truncated)
2: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    inet 169.254.172.97/16 brd 169.254.255.255 scope global usb0
(truncated)

iex> Nerves.Network.Udhcpc.renew(Process.whereis(Nerves.Udhcpc))

00:02:42.695 [debug] DHCPManager.EventHandler(usb0) ifup

00:02:42.882 [debug] IP Address Changed

00:02:42.887 [debug] Reconfiguring mDNS IP: nil

00:02:42.895 [debug] Start Network Manager

00:02:43.053 [debug] DHCPManager(usb0, dhcp) got event :ifup

00:02:43.091 [debug] udhcpc: deconfigure usb0

00:02:43.111 [debug] DHCPManager.EventHandler(usb0) udhcpc :deconfig
** (exit) exited in: GenServer.call(#PID<0.165.0>, :renew, 5000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :supervisor.handle_call/3
            (stdlib) supervisor.erl:402: :supervisor.handle_call(:renew, {#PID<0.96.0>, #Reference<0.3115819352.537133057.142767>}, {:state, {:local, Nerves.Udhcpc}, :one_for_one, [{:child, #PID<0.166.0>, Nerves.Udhcpc.PIDPartition0, {Registry.Partition, :start_link, [Nerves.Udhcpc.PIDPartition0, {:duplicate, Nerves.Udhcpc, 0, 1, Nerves.Udhcpc.KeyPartition0, Nerves.Udhcpc.PIDPartition0, []}]}, :permanent, 5000, :worker, [Registry.Partition]}], :undefined, 3, 5, [], 0, Registry.Supervisor, {:duplicate, Nerves.Udhcpc, 1, [], [{-1, {:duplicate, 1, nil, nil, []}}, {-2, {:duplicate, 1, nil}}]}})
            (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:774: GenServer.call/3
iex(7)>
00:02:43.237 [error] GenServer Nerves.Udhcpc terminating
** (FunctionClauseError) no function clause matching in :supervisor.handle_call/3
    (stdlib) supervisor.erl:402: :supervisor.handle_call(:renew, {#PID<0.96.0>, #Reference<0.3115819352.537133057.142767>}, {:state, {:local, Nerves.Udhcpc}, :one_for_one, [{:child, #PID<0.166.0>, Nerves.Udhcpc.PIDPartition0, {Registry.Partition, :start_link, [Nerves.Udhcpc.PIDPartition0, {:duplicate, Nerves.Udhcpc, 0, 1, Nerves.Udhcpc.KeyPartition0, Nerves.Udhcpc.PIDPartition0, []}]}, :permanent, 5000, :worker, [Registry.Partition]}], :undefined, 3, 5, [], 0, Registry.Supervisor, {:duplicate, Nerves.Udhcpc, 1, [], [{-1, {:duplicate, 1, nil, nil, []}}, {-2, {:duplicate, 1, nil}}]}})
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.96.0>): :renew
State: {:state, {:local, Nerves.Udhcpc}, :one_for_one, [{:child, #PID<0.166.0>, Nerves.Udhcpc.PIDPartition0, {Registry.Partition, :start_link, [Nerves.Udhcpc.PIDPartition0, {:duplicate, Nerves.Udhcpc, 0, 1, Nerves.Udhcpc.KeyPartition0, Nerves.Udhcpc.PIDPartition0, []}]}, :permanent, 5000, :worker, [Registry.Partition]}], :undefined, 3, 5, [], 0, Registry.Supervisor, {:duplicate, Nerves.Udhcpc, 1, [], [{-1, {:duplicate, 1, nil, nil, []}}, {-2, {:duplicate, 1, nil}}]}}
Client #PID<0.96.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:771: GenServer.call/3
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:237: :elixir.eval_forms/4
    (iex) lib/iex/evaluator.ex:219: IEx.Evaluator.handle_eval/5
    (iex) lib/iex/evaluator.ex:200: IEx.Evaluator.do_eval/3
    (iex) lib/iex/evaluator.ex:178: IEx.Evaluator.eval/3
    (iex) lib/iex/evaluator.ex:77: IEx.Evaluator.loop/1


00:02:44.132 [error] GenServer #PID<0.176.0> terminating
** (FunctionClauseError) no function clause matching in String.split/3
    (elixir) lib/string.ex:366: String.split(nil, ".", [])
    (nerves_init_gadget) lib/nerves_init_zero/network_manager.ex:41: Nerves.InitGadget.NetworkManager.configure_mdns/1
    (nerves_init_gadget) lib/nerves_init_zero/network_manager.ex:26: Nerves.InitGadget.NetworkManager.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:system_registry, :global, %{config: %{network_interface: %{:usb0 => [ipv4_address_method: :dhcp], "usb0" => [ipv4_address_method: :linklocal]}}, state: %{"devices" => %{"platform" => %{"alarmtimer" => %{"driver" => "alarmtimer", "modalias" => "platform:alarmtimer", "seqnum" => "472", "subsystem" => "platform"}, "clocks" => %{"clocks:clock@0" => %{"modalias" => "of:NclockT<NULL>Cfixed-clock", "of_compatible_0" => "fixed-clock", "of_compatible_n" => "1", "of_fullname" => "/clocks/clock@0", "of_name" => "clock", "seqnum" => "470", "subsystem" => "platform"}, "clocks:clock@1" => %{"modalias" => "of:NclockT<NULL>Cfixed-clock", "of_compatible_0" => "fixed-clock", "of_compatible_n" => "1", "of_fullname" => "/clocks/clock@1", "of_name" => "clock", "seqnum" => "469", "subsystem" => "platform"}, "clocks:clock@2" => %{"modalias" => "of:NclockT<NULL>Cfixed-clock", "of_compatible_0" => "fixed-clock", "of_compatible_n" => "1", "of_fullname" => "/clocks/clock@2", "of_name" => "clock", "seqnum" => "468", "subsystem" => "platform"}, "clocks:clock@3" => %{"modalias" => "of:NclockT<NULL>Cfixed-clock", "of_compatible_0" => "fixed-clock", "of_compatible_n" => "1", "of_fullname" => "/clocks/clock@3", "of_name" => "clock", "seqnum" => "467", "subsystem" => "platform"}, "clocks:clock@4" => %{"modalias" => "of:NclockT<NULL>Cfixed-clock", "of_compatible_0" => "fixed-clock", "of_compatible_n" => "1", "of_fullname" => "/clocks/clock@4", "of_name" => "clock", "seqnum" => "466", "subsystem" => "platform"}, "clocks:clock@5" => %{"modalias" => "of:NclockT<NULL>Cfixed-factor-clock", "of_compatible_0" => "fixed-factor-clock", "of_compatible_n" => "1", "of_fullname" => "/clocks/clock@5", "of_name" => "clock", "seqnum" => "465", "subsystem" => "platform"}, "clocks:clock@6" => %{"modalias" => "of:NclockT<NULL>Cfixed-clock", "of_compatible_0" => "fixed-clock", "of_compatible_n" => "1", "of_fullname" => "/clocks/clock@6", "of_name" => "clock", "seqnum" => "464", "subsystem" => "platform"}, "modalias" => "of:NclocksT<NULL>Csimple-bus", "of_compatible_0" => "simple-bus", "of_compatible_n" => "1", "of_fullname" => "/clocks", "of_name" => "clocks", "seqnum" => "471", "subsystem" => "platform"}, "regulatory.0" => %{"modalias" => "platform:regulatory", "seqnum" => "463", "subsystem" => "platform"}, "soc" => %{"20003000.timer" => %{"modalias" => "of:NtimerT<NULL>Cbrcm,bcm2835-system-timer", "of_compatible_0" => "brcm,bcm2835-system-timer", "of_compatible_n" => "1", "of_fullname" => "/soc/timer@7e003000", "of_name" => "timer", "seqnum" => "526", "subsystem" => "platform"}, "20007000.dma" => %{"dma" => %{"dma0chan0" => %{"seqnum" => "503", "subsystem" => "dma"}, "dma0chan1" => %{"seqnum" => "502", "subsystem" => "dma"}, "dma0chan2" => %{"seqnum" => "501", "subsystem" => "dma"}, "dma0chan3" => %{"seqnum" => "500", "subsystem" => "dma"}, "dma0chan4" => %{"seqnum" => "499", "subsystem" => "dma"}, "dma0chan5" => %{"seqnum" => "498", "subsystem" => "dma"}, "dma0chan6" => %{"seqnum" => "497", "subsystem" => "dma"}, "dma0chan7" => %{"seqnum" => "496", "subsystem" => "dma"}, "dma0chan8" => %{"seqnum" => "495", "subsystem" => "dma"}, "dma0chan9" => %{"seqnum" => "494", "subsystem" => "dma"}}, "driver" => "bcm2835-dma", "modalias" => "of:NdmaT<NULL>Cbrcm,bcm2835-dma", "of_compatible_0" => "brcm,bcm2835-dma", "of_compatible_n" => "1", "of_fullname" => "/soc/dma@7e007000", "of_name" => "dma", "seqnum" => "493", "subsystem" => "platform"}, "2000b200.interrupt-controller" => %{"modalias" => "of:Ninterrupt-controllerT<NULL>Cbrcm,bcm2835-armctrl-ic", "of_compatible_0" => "brcm,bcm2835-armctrl-ic", "of_compatible_n" => "1", "of_fullname" => "/soc/interrupt-controller@7e00b200", "of_name" => "interrupt-controller", "seqnum" => "508", "subsystem" => "platform"}, "2000b840.vchiq" => %{"driver" => "bcm2835_vchiq", "modalias" => "of:NvchiqT<NULL>Cbrcm,bcm2835-vchiq", "of_compatible_0" => "brcm,bcm2835-vchiq", "of_compatible_n" => "1", "of_fullname" => "/soc/vchiq", "of_name" => "vchiq", "seqnum" => "473", "subsystem" => "platform"}, "2000b880.mailbox" => %{"driver" => "bcm2835-mbox", "modalias" => "of:NmailboxT<NULL>Cbrcm,bcm2835-mbox", "of_compatible_0" => "brcm,bcm2835-mbox", "of_compatible_n" => "1", "of_fullname" => "/soc/mailbox@7e00b800", "of_name" => "mailbox", "seqnum" => "476", "subsystem" => "platform"}, "20100000.watchdog" => %{"misc" => %{"watchdog" => %{"devname" => "watchdog", "major" => "10", "minor" => "130", "seqnum" => "656", "subsystem" => "misc"}}, "modalias" => "of:NwatchdogT<NULL>Cbrcm,bcm2835-pm-wdt", "of_compatible_0" => "brcm,bcm2835-pm-wdt", "of_compatible_n" => "1", "of_fullname" => "/soc/watchdog@7e100000", "of_name" => "watchdog", "seqnum" => "515", "subsystem" => "platform", "watchdog" => %{"watchdog0" => %{"devname" => "watchdog0", "major" => "253", "minor" => "0", "seqnum" => "657", "subsystem" => "watchdog"}}}, "20104000.rng" => %{"driver" => "bcm2835-rng", "modalias" => "of:NrngT<NULL>Cbrcm,bcm2835-rng", "of_compatible_0" => "brcm,bcm2835-rng", "of_compatible_n" => "1", "of_fullname" => "/soc/rng@7e104000", "of_name" => "rng", "seqnum" => "527", "subsystem" => "platform"}, "20200000.gpio" => %{"driver" => "pinctrl-bcm2835", "gpio" => %{"gpiochip0" => %{"seqnum" => "478", "subsystem" => "gpio"}}, "modalias" => "of:NgpioT<NULL>Cbrcm,bcm2835-gpio", "of_compatible_0" => "brcm,bcm2835-gpio", "of_compatible_n" => "1", "of_fullname" => "/soc/gpio@7e200000", "of_name" => "gpio", "seqnum" => "477", "subsystem" => "platform"}, "20200000.gpiomem" => %{"driver" => "gpiomem-bcm2835", "modalias" => "of:NgpiomemT<NULL>Cbrcm,bcm2835-gpiomem", "of_compatible_0" => "brcm,bcm2835-gpiomem", "of_compatible_n" => "1", "of_fullname" => "/soc/gpiomem", "of_name" => "gpiomem", "seqnum" => "482", "subsystem" => "platform"}, "20201000.uart" => %{"amba_id" => "00241011", "driver" => "uart-pl011", "modalias" => "amba:d00241011", "of_alias_0" => "serial0", "of_alias_1" => "uart0", "of_compatible_0" => "arm,pl011", "of_compatible_1" => "arm,primecell", "of_compatible_n" => "2", "of_fullname" => "/soc/uart@7e201000", "of_name" => "uart", "seqnum" => "506", "subsystem" => "amba", "tty" => %{"ttyAMA0" => %{"devname" => "ttyAMA0", "major" => "204", "minor" => "64", "seqnum" => "507", "subsystem" => "tty"}}}, "20202000.sdhost" => %{"driver" => "sdhost-bcm2835", "mmc_host" => %{"mmc0" => %{"mmc0:1234" => %{"block" => %{"mmcblk0" => %{"devname" => "mmcblk0", "devtype" => "disk", "major" => "179", "minor" => "0", "mmcblk0p1" => %{"devname" => "mmcblk0p1", "devtype" => "partition", "major" => "179", "minor" => "1", "seqnum" => "490", "subsystem" => "block"}, "mmcblk0p2" => %{"devname" => "mmcblk0p2", "devtype" => "partition", "major" => "179", "minor" => "2", "seqnum" => "489", "subsystem" => "block"}, "mmcblk0p3" => %{"devname" => "mmcblk0p3", "devtype" => "partition", "major" => "179", "minor" => "3", "seqnum" => "488", "subsystem" => "block"}, "seqnum" => "487", "subsystem" => "block"}}, "driver" => "mmcblk", "mmc_name" => "SA04G", "mmc_type" => "SD", "modalias" => "mmc:block", "seqnum" => "486", "subsystem" => "mmc"}, "seqnum" => "485", "subsystem" => "mmc_host"}}, "modalias" => "of:NsdhostT<NULL>Cbrcm,bcm2835-sdhost", "of_compatible_0" => "brcm,bcm2835-sdhost", "of_compatible_n" => "1", "of_fullname" => "/soc/sdhost@7e202000", "of_name" => "sdhost", "seqnum" => "484", "subsystem" => "platform"}, "20204000.spi" => %{"driver" => "spi-bcm2835", "modalias" => "of:NspiT<NULL>Cbrcm,bcm2835-spi", "of_alias_0" => "spi0", "of_compatible_0 (truncated)

00:02:46.246 [debug] udhcpc: bound usb0: IP=192.168.2.5, dns="192.168.2.1"

00:02:46.247 [debug] DHCPManager.EventHandler(usb0) udhcpc :bound

00:02:46.326 [debug] IP Address Changed

00:02:46.327 [debug] Reconfiguring mDNS IP: "192.168.2.5"

iex(9)> :os.cmd('ip addr') |> IO.puts
(truncated)
2: usb0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether c6:60:6e:32:f0:93 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.5/24 brd 192.168.2.255 scope global usb0
       valid_lft forever preferred_lft forever
    inet6 fe80::c460:6eff:fe32:f093/64 scope link
       valid_lft forever preferred_lft forever
(truncated)
```

**Comment by ConnorRigby** [comment]
I believe this will have been fixed with #64 checking right now
