### ISSUE TITLE
Fix reporting of unhandled DHCP events

### ISSUE THREAD

**Issue by webengineer-max** [nerves-project/nerves_network#43]
Hello

Reporting at https://github.com/nerves-project/nerves_network/blob/v0.3.4/lib/nerves_network/dhcp_manager.ex#L212 is broken with following error 

```
[error]  GenServer :"Nerves.Network.Interface.eth0" terminating ** (Protocol.UndefinedError) protocol String.Chars not implemented for {:renew, %{domain: "", ifname: "eth0", ipv4_address: "192.168.174.55", ipv4_broadcast: "192.168.174.255", ipv4_gateway: "192.168.174.98", ipv4_subnet_mask: "255.255.255.0", nameservers: ["192.168.174.98"]}}     (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1     (elixir) lib/string/chars.ex:22: String.Chars.to_string/1     (nerves_network) lib/nerves_network/dhcp_manager.ex:212: Nerves.Network.DHCPManager.consume/3     (nerves_network) lib/nerves_network/dhcp_manager.ex:104: Nerves.Network.DHCPManager.handle_info/2     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 Last message: {Nerves.Udhcpc, :renew, %{domain: "", ifname: "eth0", ipv4_address: "192.168.174.55", ipv4_broadcast: "192.168.174.255", ipv4_gateway: "192.168.174.98", ipv4_subnet_mask: "255.255.255.0", nameservers: ["192.168.174.98"]}}
```

-- 
Max

**Comment by webengineer-max** [comment]
Pushed https://github.com/nerves-project/nerves_network/pull/44
