### ISSUE TITLE
wpa-eap networks don't work

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_network#74]
```elixir
Nerves.WpaSupplicant.set_network(wpa, ssid: ssid, key_mgmt: :"WPA-EAP", pairwise: :"CCMP TKIP", identity: username, group: "CCMP TKIP", password: "hash:#{pw_hash}", phase1: "peaplabel=0", phase2: "auth=MSCHAPV2")
```

Full disclaimer, i don't know if all of these fields are correct, but i _personally_ believe they should be. wpa_ctrl receives a ca cert that tries to get parsed into an atom for some reason.

**Comment by klingtnet** [comment]
I also failed to connect to an WPA enterprise network. What I tried is to translate a working `wpa_supplicant.conf` into Nerves Network settings.

**Comment by fhunleth** [comment]
@klingtnet Could you point out where the documentation is broken so that it can be fixed?

**Comment by klingtnet** [comment]
> I've been slowly working towards implementing this. @klingtnet Could you post your working config, as well as any error logs if you can capture them?

```conf
network={
	ssid=<ssid>
	scan_ssid=1
	key_mgmt=WPA-EAP
	pairwise=CCMP TKIP
	group=CCMP TKIP
	eap=PEAP
	identity=<username>
	password=<password>
	phase1="peapver=auto"
	phase2="MSCHAPV2"
}
```

**Comment by ConnorRigby** [comment]
>  the serial console would only work one out of 5 or more tries.

Unfortunately this has been identified as a bug in Raspberry Pi's kernel. I've personally noticed it happen when the *HOST* machine is on Linux kernel newer than 4.9. Specifically both of my Arch Linux installations have produced this issue. i _thought_ upgrading my host machine to Linux 4.20 fixed it but i noticed it crop back up again. As far as i know there is no fix for it as of yet.

**Comment by ConnorRigby** [comment]
I've reopened an issue about this. https://github.com/nerves-project/nerves_system_rpi0/issues/79
I closed it when i believed that linux kernel 4.20 fixed it, but that doesn't seem to be the case.

**Comment by ConnorRigby** [comment]
okay i have a error log of what happens when one tries to use eap networks:
```
Child :"Nerves.Network.Interface.wlan0" of Supervisor Nerves.Network.IFSupervisor terminated
** (exit) an exception was raised:
    ** (SystemLimitError) a system limit has been reached
        :erlang.binary_to_atom("CTRL-EVENT-EAP-PEER-CERT depth=0 subject='/CN=REDACTED' cert=REALLY_LONG_CERT_THAT_HAS_BEEN_REDACTED", :utf8)
        (nerves_wpa_supplicant) lib/nerves_wpa_supplicant/messages.ex:140: Nerves.WpaSupplicant.Messages.decode_notif/1
        (nerves_wpa_supplicant) lib/nerves_wpa_supplicant.ex:268: Nerves.WpaSupplicant.handle_wpa/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Pid: #PID<0.3199.0>
Start Call: Nerves.Network.WiFiManager.start_link("wlan0", [networks: [[ssid: "REDACTED", scan_ssid: 1, key_mgmt: :"WPA-EAP", pairwise: :"CCMP TKIP", group: :"CCMP TKIP", eap: :PEAP, identity: "Rob.niedermeyer", password: "Beagle71!", phase1: "peapver=auto", phase2: "MSCHAPV2", ipv4_address_method: :dhcp]]], [name: :"Nerves.Network.Interface.wlan0"])
Restart: :permanent
Shutdown: 5000
Type: :worker
```

**Comment by ConnorRigby** [comment]
This will be fixed as soon as [#24 on nerves_wpa_supplicant](https://github.com/nerves-project/nerves_wpa_supplicant/pull/24) is merged
